[build]
  command = "npm run build"
  publish = "Paginaventa"          # todo en minúsculas
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/store.html"
  status = 200

[[redirects]]
  from = "/create-checkout-session"
  to = "/.netlify/functions/server"
  status = 200