[build]
  command = "npm run build"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/store.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;"
    